name: QuantAI Agent

on:
  schedule:
    - cron: '0 8 * * *'  # Tous les jours à 8h UTC (10h à Paris)
  workflow_dispatch:     # Lancement manuel possible

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run agent
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python3 main.py
